// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.1
// source: rpc/perms.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Perms_Check_FullMethodName = "/perms.Perms/Check"
)

// PermsClient is the client API for Perms service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PermsClient interface {
	Check(ctx context.Context, in *AccessRequest, opts ...grpc.CallOption) (*AccessResponse, error)
}

type permsClient struct {
	cc grpc.ClientConnInterface
}

func NewPermsClient(cc grpc.ClientConnInterface) PermsClient {
	return &permsClient{cc}
}

func (c *permsClient) Check(ctx context.Context, in *AccessRequest, opts ...grpc.CallOption) (*AccessResponse, error) {
	out := new(AccessResponse)
	err := c.cc.Invoke(ctx, Perms_Check_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PermsServer is the server API for Perms service.
// All implementations must embed UnimplementedPermsServer
// for forward compatibility
type PermsServer interface {
	Check(context.Context, *AccessRequest) (*AccessResponse, error)
	mustEmbedUnimplementedPermsServer()
}

// UnimplementedPermsServer must be embedded to have forward compatible implementations.
type UnimplementedPermsServer struct {
}

func (UnimplementedPermsServer) Check(context.Context, *AccessRequest) (*AccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedPermsServer) mustEmbedUnimplementedPermsServer() {}

// UnsafePermsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PermsServer will
// result in compilation errors.
type UnsafePermsServer interface {
	mustEmbedUnimplementedPermsServer()
}

func RegisterPermsServer(s grpc.ServiceRegistrar, srv PermsServer) {
	s.RegisterService(&Perms_ServiceDesc, srv)
}

func _Perms_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermsServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Perms_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermsServer).Check(ctx, req.(*AccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Perms_ServiceDesc is the grpc.ServiceDesc for Perms service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Perms_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "perms.Perms",
	HandlerType: (*PermsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _Perms_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/perms.proto",
}
